### ISSUE TITLE
bug in installer for debian.

### ISSUE THREAD

**Issue by billthecatt** [zeropingheroes/lancache-filebeat#1]
Something is up with the installer...

essentially, it's adding a https link to the sources.list.d folder and then asking to do an apt-get update.. before installing apt-transport-https:

echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-6.x.list

then:

/usr/bin/apt install -y apt-transport-https \
                        filebeat

this causes the following error:

E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?
E: Failed to fetch https://artifacts.elastic.co/packages/6.x/apt/dists/stable/InRelease

All of this to say, you should prob call apt-install of apt-transport-https before adding https items to the apt sources.. then call the install of filebeat after that's done..

Thanks again for a great project!

**Comment by ilumos** [comment]
Nice catch, thank you
